In [1]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [2]:
from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = "cuda")
classifier("I love this!")

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

E:\Learning\Python\book-recommender\.venv\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\mdzak\.cache\huggingface\hub\models--j-hartmann--emotion-english-distilroberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  329MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  329MB

model.safetensors: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528676815330982},
  {'label': 'neutral', 'score': 0.005764597095549107},
  {'label': 'anger', 'score': 0.004419785924255848},
  {'label': 'sadness', 'score': 0.002092393347993493},
  {'label': 'disgust', 'score': 0.0016119939973577857},
  {'label': 'fear', 'score': 0.0004138521908316761}]]

In [3]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [4]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548410654067993},
  {'label': 'neutral', 'score': 0.16985194385051727},
  {'label': 'sadness', 'score': 0.11640904098749161},
  {'label': 'surprise', 'score': 0.02070070616900921},
  {'label': 'disgust', 'score': 0.01910071261227131},
  {'label': 'joy', 'score': 0.015161263756453991},
  {'label': 'anger', 'score': 0.003935149405151606}]]

- The description has a mix of different emotions and the highest category being fear doesn't track when you actually read the whole description.
- Thus, classifying based on individual sentences makes more sense.

In [5]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296027541160583},
  {'label': 'neutral', 'score': 0.140385702252388},
  {'label': 'fear', 'score': 0.06816215813159943},
  {'label': 'joy', 'score': 0.047942426055669785},
  {'label': 'anger', 'score': 0.009156357496976852},
  {'label': 'disgust', 'score': 0.002628474263474345},
  {'label': 'sadness', 'score': 0.0021221607457846403}],
 [{'label': 'neutral', 'score': 0.4493708610534668},
  {'label': 'disgust', 'score': 0.27359139919281006},
  {'label': 'joy', 'score': 0.10908285528421402},
  {'label': 'sadness', 'score': 0.09362731128931046},
  {'label': 'anger', 'score': 0.04047828167676926},
  {'label': 'surprise', 'score': 0.02697020024061203},
  {'label': 'fear', 'score': 0.006879059597849846}],
 [{'label': 'neutral', 'score': 0.6462165713310242},
  {'label': 'sadness', 'score': 0.24273282289505005},
  {'label': 'disgust', 'score': 0.04342262074351311},
  {'label': 'surprise', 'score': 0.028300536796450615},
  {'label': 'joy', 'score': 0.01421146560460329},
  {'label': 'fear', 'score': 0.014084091410040855},
  {'label': 'anger', 'score': 0.011031880974769592}],
 [{'label': 'fear', 'score': 0.928167998790741},
  {'label': 'anger', 'score': 0.03219098225235939},
  {'label': 'neutral', 'score': 0.012808718718588352},
  {'label': 'sadness', 'score': 0.008756889030337334},
  {'label': 'surprise', 'score': 0.00859792623668909},
  {'label': 'disgust', 'score': 0.008431852795183659},
  {'label': 'joy', 'score': 0.0010455820010975003}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104170888662338},
  {'label': 'disgust', 'score': 0.00648059556260705},
  {'label': 'fear', 'score': 0.005393994972109795},
  {'label': 'surprise', 'score': 0.0022869433742016554},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338779289275408}],
 [{'label': 'joy', 'score': 0.9327970147132874},
  {'label': 'disgust', 'score': 0.037717871367931366},
  {'label': 'neutral', 'score': 0.015891967341303825},
  {'label': 'sadness', 'score': 0.006444553378969431},
  {'label': 'anger', 'score': 0.0050250268541276455},
  {'label': 'surprise', 'score': 0.0015812092460691929},
  {'label': 'fear', 'score': 0.0005423107650130987}],
 [{'label': 'joy', 'score': 0.6528706550598145},
  {'label': 'neutral', 'score': 0.2542746365070343},
  {'label': 'surprise', 'score': 0.06808312982320786},
  {'label': 'sadness', 'score': 0.009908992797136307},
  {'label': 'disgust', 'score': 0.006512203253805637},
  {'label': 'anger', 'score': 0.004821316804736853},
  {'label': 'fear', 'score': 0.003529016859829426}],
 [{'label': 'neutral', 'score': 0.5494765043258667},
  {'label': 'sadness', 'score': 0.1116902083158493},
  {'label': 'disgust', 'score': 0.10400675237178802},
  {'label': 'surprise', 'score': 0.07876554131507874},
  {'label': 'anger', 'score': 0.06413368880748749},
  {'label': 'fear', 'score': 0.051362842321395874},
  {'label': 'joy', 'score': 0.04056443274021149}]]

In [6]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [9]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [10]:
predictions[3]

[{'label': 'fear', 'score': 0.928167998790741},
 {'label': 'anger', 'score': 0.03219098225235939},
 {'label': 'neutral', 'score': 0.012808718718588352},
 {'label': 'sadness', 'score': 0.008756889030337334},
 {'label': 'surprise', 'score': 0.00859792623668909},
 {'label': 'disgust', 'score': 0.008431852795183659},
 {'label': 'joy', 'score': 0.0010455820010975003}]

- the classifier seems to be working correctly.

- Assign score to each sentence, and assign highest score of each emotion.

In [11]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156357496976852},
 {'label': 'disgust', 'score': 0.002628474263474345},
 {'label': 'fear', 'score': 0.06816215813159943},
 {'label': 'joy', 'score': 0.047942426055669785},
 {'label': 'neutral', 'score': 0.140385702252388},
 {'label': 'sadness', 'score': 0.0021221607457846403},
 {'label': 'surprise', 'score': 0.7296027541160583}]

In [12]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise"]
isbn=[]
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}

    for prediction in predictions:
        sorted_prediction = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_prediction[index]["score"])

    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [13]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)

    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [14]:
emotion_scores

{'anger': [np.float64(0.06413368880748749),
  np.float64(0.6126189827919006),
  np.float64(0.06413368880748749),
  np.float64(0.3514832854270935),
  np.float64(0.08141238987445831),
  np.float64(0.232224702835083),
  np.float64(0.5381833910942078),
  np.float64(0.06413368880748749),
  np.float64(0.30067017674446106),
  np.float64(0.06413368880748749)],
 'disgust': [np.float64(0.27359139919281006),
  np.float64(0.34828436374664307),
  np.float64(0.10400675237178802),
  np.float64(0.15072230994701385),
  np.float64(0.18449531495571136),
  np.float64(0.7271749377250671),
  np.float64(0.15585504472255707),
  np.float64(0.10400675237178802),
  np.float64(0.27948129177093506),
  np.float64(0.1779269576072693)],
 'fear': [np.float64(0.928167998790741),
  np.float64(0.9425276517868042),
  np.float64(0.9723208546638489),
  np.float64(0.3607073724269867),
  np.float64(0.09504338353872299),
  np.float64(0.051362842321395874),
  np.float64(0.7474281191825867),
  np.float64(0.4044954478740692),
  np.float64(0.9155241250991821),
  np.float64(0.051362842321395874)],
 'joy': [np.float64(0.9327970147132874),
  np.float64(0.7044210433959961),
  np.float64(0.7672367095947266),
  np.float64(0.25188079476356506),
  np.float64(0.04056443274021149),
  np.float64(0.04337583854794502),
  np.float64(0.8725650310516357),
  np.float64(0.04056443274021149),
  np.float64(0.04056443274021149),
  np.float64(0.04056443274021149)],
 'sadness': [np.float64(0.6462165713310242),
  np.float64(0.8879395127296448),
  np.float64(0.5494765043258667),
  np.float64(0.7326857447624207),
  np.float64(0.8843896985054016),
  np.float64(0.6213921308517456),
  np.float64(0.7121944427490234),
  np.float64(0.5494765043258667),
  np.float64(0.8402895331382751),
  np.float64(0.8603722453117371)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.47588053345680237),
  np.float64(0.1116902083158493),
  np.float64(0.40799984335899353),
  np.float64(0.8202822208404541),
  np.float64(0.3544599413871765),
  np.float64(0.1116902083158493)]}

In [15]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5693/5693 [03:29<00:00, 27.16it/s]

In [16]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [17]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928168,0.932797,0.646217,0.967158,0.729603,9780002005883
1,0.612619,0.348284,0.942528,0.704421,0.887940,0.111690,0.252545,9780002261982
2,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766,9780006178736
3,0.351483,0.150722,0.360707,0.251881,0.732686,0.111690,0.078766,9780006280897
4,0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078766,9780006280934
...,...,...,...,...,...,...,...,...
5688,0.064134,0.114383,0.051363,0.400263,0.883199,0.111690,0.227765,9788173031014
5689,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625,9788179921623
5690,0.064134,0.104007,0.459269,0.759455,0.951104,0.368111,0.078766,9788185300535
5691,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766,9789027712059
5692,0.064134,0.104007,0.051363,0.991484,0.549477,0.111690,0.078766,9789042003408

In [18]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [19]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273591,0.928168,0.932797,0.646217,0.967158,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348284,0.942528,0.704421,0.887940,0.111690,0.252545
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351483,0.150722,0.360707,0.251881,0.732686,0.111690,0.078766
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184495,0.095043,0.040564,0.884390,0.475881,0.078766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5688,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883199,0.111690,0.227765
5689,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
5690,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459269,0.759455,0.951104,0.368111,0.078766
5691,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766
5692,9789042003408,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,...,'I'm Telling You Stories': Jeanette Winterson ...,9789042003408 This is a jubilant and rewarding...,Nonfiction,0.064134,0.104007,0.051363,0.991484,0.549477,0.111690,0.078766

In [20]:
books.to_csv("books_with_emotions.csv", index = False)

---