In [2]:
from langchain_community.document_loaders import DataFrameLoader
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma

C:\Users\mdzak\AppData\Local\Temp\ipykernel_21896\1879199775.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import DataFrameLoader
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

In [3]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)

In [5]:
books = pd.read_csv("books_cleaned.csv")

In [6]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_description,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,"A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an ...",2004.0,3.85,247.0,361.0,0,Gilead,"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade,..."
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles...,2000.0,3.83,241.0,5164.0,0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed p...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2TgANz74C&printsec=frontcover&img=1&zoom=1&source=gb...,"A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up unt...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on ..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5XsFcpGIC&printsec=frontcover&img=1&zoom=1&source=gb...,"Lewis' work on the nature of love divides love into four categories; Affection, Friendship, Eros...",2002.0,4.15,170.0,33684.0,0,The Four Loves,"9780006280897 Lewis' work on the nature of love divides love into four categories; Affection, Fr..."
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uVe5QK-gC&printsec=frontcover&img=1&zoom=1&source=gb...,"""In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors and thinkers, ex...",2002.0,4.09,176.0,37569.0,0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors an..."

In [7]:
loader = DataFrameLoader(books, page_content_column="tagged_description")
documents = loader.load()

In [8]:
len(documents)

5693

In [9]:
documents[0]

Document(metadata={'isbn13': 9780002005883, 'isbn10': '0002005883', 'title': 'Gilead', 'authors': 'Marilynne Robinson', 'categories': 'Fiction', 'thumbnail': 'http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'description': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.', 'published_year': 2004.0, 'average_rating': 3.85, 'num_pages': 247.0, 'ratings_count': 361.0, 'missing_description': 0, 'title_and_subtitle': 'Gilead'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

The `CharacterTextSplitter` was raising a `ValueError` because recent versions of `langchain` require `chunk_size` to be a positive integer.

A more direct and efficient approach is to load the data directly from the pandas DataFrame using `DataFrameLoader`. This avoids the intermediate step of saving to a text file and then splitting it, making the code cleaner and avoiding the error.

In [10]:
db_books = Chroma.from_documents(
    documents,
    embedding=GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-2")
)

In [11]:
# import google.generativeai as genai
#
# print("Available embedding models:")
# for m in genai.list_models():
#   if 'embedContent' in m.supported_generation_methods:
#     print(m.name)

In [12]:
query = "A book to teach children about nature"

docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='23d5b49d-ff6a-4335-aeb6-224cdc16ec3f', metadata={'isbn10': '006757520X', 'categories': 'Nature', 'average_rating': 4.39, 'missing_description': 0, 'thumbnail': 'http://books.google.com/books/content?id=Zee5SAOqO2UC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'title_and_subtitle': 'The Sense of Wonder', 'title': 'The Sense of Wonder', 'isbn13': 9780067575208, 'num_pages': 112.0, 'published_year': 1998.0, 'authors': 'Rachel Carson', 'ratings_count': 1160.0, 'description': 'First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the "living music" of insects in the underbrush. "If a child is to keep alive his inborn sense of wonder." Writes Carson, "he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in." The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time.'}, page_content='9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the "living music" of insects in the underbrush. "If a child is to keep alive his inborn sense of wonder." Writes Carson, "he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in." The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time.'),
 Document(id='c6b44437-763c-4f3e-a499-f7dafaef8b0b', metadata={'isbn13': 9780789458209, 'missing_description': 0, 'categories': 'Juvenile Nonfiction', 'ratings_count': 5.0, 'average_rating': 4.07, 'thumbnail': 'http://books.google.com/books/content?id=Qwsqj2INT1QC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'published_year': 2000.0, 'title_and_subtitle': 'Tree', 'description': 'Photographs and text explore the anatomy and life cycle of trees, examining the different kinds of bark, seeds, and leaves, the commercial processing of trees to make lumber, the creatures that live in trees, and other aspects.', 'num_pages': 64.0, 'authors': 'David Burnie', 'title': 'Tree', 'isbn10': '0789458209'}, page_content='9780789458209 Photographs and text explore the anatomy and life cycle of trees, examining the different kinds of bark, seeds, and leaves, the commercial processing of trees to make lumber, the creatures that live in trees, and other aspects.'),
 Document(id='3e8059d7-14e8-4c00-bb49-c246cae33290', metadata={'thumbnail': 'http://books.google.com/books/content?id=RU1_QgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'num_pages': 164.0, 'ratings_count': 672.0, 'description': 'It has always been a pleasure to me to watch the flowers and insects in their struggle to keep alive. When the sun was hot they would come to life again, and give themselves up for an hour or so to the old delight; the big, strong flies were just as much alive as in midsummer. There was a peculiar sort of earth-bug here that I had not seen before--little yellow things, no bigger than a small-type comma, yet they could jump several thousand times their own length. Think of the strength of such a body in proportion to its size! There is a tiny spider here with its hinder part like a pale yellow pearl.', 'title': 'The Wanderer', 'published_year': 2001.0, 'title_and_subtitle': 'The Wanderer', 'missing_description': 0, 'average_rating': 3.96, 'categories': 'English fiction', 'authors': 'Knut Hamsun;Gunnvor Stallybrass', 'isbn13': 9780285647879, 'isbn10': '0285647873'}, page_content='9780285647879 It has always been a pleasure to me to watch the flowers and insects in their struggle to keep alive. When the sun was hot they would come to life again, and give themselves up for an hour or so to the old delight; the big, strong flies were just as much alive as in midsummer. There was a peculiar sort of earth-bug here that I had not seen before--little yellow things, no bigger than a small-type comma, yet they could jump several thousand times their own length. Think of the strength of such a body in proportion to its size! There is a tiny spider here with its hinder part like a pale yellow pearl.'),
 Document(id='77c56d4b-3b3b-4dcc-9f91-1c262bc8bcff', metadata={'ratings_count': 80.0, 'categories': 'Juvenile Nonfiction', 'published_year': 2002.0, 'isbn10': '0761316809', 'title_and_subtitle': "It's Winter!", 'title': "It's Winter!", 'thumbnail': 'http://books.google.com/books/content?id=eSCmKfZGvmcC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'num_pages': 32.0, 'isbn13': 9780761316800, 'average_rating': 3.63, 'authors': 'Linda Glaser', 'description': 'A child observes the coming of winter and its effects on the weather, animals, and plants. Includes suggestions for wintertime activities.', 'missing_description': 0}, page_content='9780761316800 A child observes the coming of winter and its effects on the weather, animals, and plants. Includes suggestions for wintertime activities.'),
 Document(id='d76bbbd2-7e9a-4ab4-ab93-bd13298deead', metadata={'missing_description': 0, 'isbn10': '0786808063', 'isbn13': 9780786808069, 'thumbnail': 'http://books.google.com/books/content?id=X9a4PAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'average_rating': 3.89, 'published_year': 2001.0, 'authors': 'Marilyn Singer;Julie Aigner-Clark', 'title': 'Baby Einstein: Neighborhood Animals', 'categories': 'Juvenile Fiction', 'description': 'Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.', 'ratings_count': 180.0, 'title_and_subtitle': 'Baby Einstein: Neighborhood Animals', 'num_pages': 16.0}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='afdb3cbe-3cb8-43d4-bceb-71e92534eb49', metadata={'description': 'Discusses the reckless annihilation of fish and birds by the use of pesticides and warns of the possible genetic effects on humans.', 'title_and_subtitle': 'Silent Spring', 'thumbnail': 'http://books.google.com/books/content?id=HeR1l0V0r54C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'average_rating': 3.97, 'published_year': 2002.0, 'num_pages': 378.0, 'ratings_count': 28033.0, 'title': 'Silent Spring', 'categories': 'Nature', 'isbn13': 9780618249060, 'missing_description': 0, 'authors': 'Rachel Carson', 'isbn10': '0618249060'}, page_content='9780618249060 Discusses the reckless annihilation of fish and birds by the use of pesticides and warns of the possible genetic effects on humans.'),
 Document(id='db01fdf5-e002-45fa-9da0-2cd1132d9143', metadata={'average_rating': 4.0, 'thumbnail': 'http://books.google.com/books/content?id=1DsEAAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'ratings_count': 8.0, 'authors': 'David Burnie', 'title_and_subtitle': 'Flowers', 'missing_description': 0, 'published_year': 1997.0, 'isbn10': '0789422131', 'num_pages': 64.0, 'title': 'Flowers', 'description': 'Describes the physical characteristics and life cycles of flowers and examines kinds of garden flowers, woodland flowers, desert flowers, and others.', 'categories': 'Juvenile Nonfiction', 'isbn13': 9780789422132}, page_content='9780789422132 Describes the physical characteristics and life cycles of flowers and examines kinds of garden flowers, woodland flowers, desert flowers, and others.'),
 Document(id='dd344dce-8239-4a54-b147-c057120e41d7', metadata={'average_rating': 4.15, 'title': 'Teach Your Child to Read in 100 Easy Lessons', 'isbn10': '0671631985', 'categories': 'Education', 'title_and_subtitle': 'Teach Your Child to Read in 100 Easy Lessons', 'authors': 'Siegfried Engelmann;Phyllis Haddox;Elaine Bruner', 'ratings_count': 2083.0, 'description': 'With more than half a million copies in print, Teach Your Child to Read in 100 Easy Lessons is the definitive guide to giving your child the reading skills needed now for a better chance at tomorrow, while bringing you and your child closer together. Is your child halfway through first grade and still unable to read? Is your preschooler bored with coloring and ready for reading? Do you want to help your child read, but are afraid you’ll do something wrong? Teach Your Child to Read in 100 Easy Lessons is a complete, step-by-step program that shows patents simply and clearly how to teach their children to read. Twenty minutes a day is all you need, and within 100 teaching days your child will be reading on a solid second-grade reading level. It’s a sensible, easy-to-follow, and enjoyable way to help your child gain the essential skills of reading. Everything you need is here—no paste, no scissors, no flash cards, no complicated directions—just you and your child learning together. One hundred lessons, fully illustrated and color-coded for clarity, give your child the basic and more advanced skills needed to become a good reader.', 'num_pages': 395.0, 'isbn13': 9780671631987, 'missing_description': 0, 'published_year': 1986.0, 'thumbnail': 'http://books.google.com/books/content?id=MUucJV0dRaIC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'}, page_content='9780671631987 With more than half a million copies in print, Teach Your Child to Read in 100 Easy Lessons is the definitive guide to giving your child the reading skills needed now for a better chance at tomorrow, while bringing you and your child closer together. Is your child halfway through first grade and still unable to read? Is your preschooler bored with coloring and ready for reading? Do you want to help your child read, but are afraid you’ll do something wrong? Teach Your Child to Read in 100 Easy Lessons is a complete, step-by-step program that shows patents simply and clearly how to teach their children to read. Twenty minutes a day is all you need, and within 100 teaching days your child will be reading on a solid second-grade reading level. It’s a sensible, easy-to-follow, and enjoyable way to help your child gain the essential skills of reading. Everything you need is here—no paste, no scissors, no flash cards, no complicated directions—just you and your child learning together. One hundred lessons, fully illustrated and color-coded for clarity, give your child the basic and more advanced skills needed to become a good reader.'),
 Document(id='0135e165-9a0b-4ed2-bd42-4599a474015b', metadata={'description': 'A very special puddle sets Violet the mouse off on her latest nature discovery. It is through this puddle that Violet observes the effect rain has on the world around her. A Mylar puddle on the last page offers children a chance to see their reflection in a puddle, just like Violet!', 'thumbnail': 'http://books.google.com/books/content?id=95IIAAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'isbn13': 9780786808717, 'published_year': 2002.0, 'isbn10': '0786808713', 'ratings_count': 16.0, 'title': 'Baby Einstein: What Does Violet See? Raindrops and Puddles', 'categories': 'Juvenile Fiction', 'average_rating': 3.25, 'num_pages': 18.0, 'authors': 'Julie Aigner-Clark', 'missing_description': 0, 'title_and_subtitle': 'Baby Einstein: What Does Violet See? Raindrops and Puddles'}, page_content='9780786808717 A very special puddle sets Violet the mouse off on her latest nature discovery. It is through this puddle that Violet observes the effect rain has on the world around her. A Mylar puddle on the last page offers children a chance to see their reflection in a puddle, just like Violet!'),
 Document(id='06859599-aaa5-4e19-82fe-b81bd0d46258', metadata={'description': 'Essays by revisionist historians, scientists, and cultural critics explore the connection between nature and American culture, analyzing how it is packaged and presented at places such as Sea World and the Nature Company stores', 'isbn10': '0393315118', 'missing_description': 0, 'thumbnail': 'http://books.google.com/books/content?id=w04mjve7XekC&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'title_and_subtitle': 'Uncommon Ground: Rethinking the Human Place in Nature', 'isbn13': 9780393315110, 'average_rating': 4.16, 'title': 'Uncommon Ground: Rethinking the Human Place in Nature', 'published_year': 1996.0, 'categories': 'Law', 'authors': 'William Cronon', 'ratings_count': 649.0, 'num_pages': 560.0}, page_content='9780393315110 Essays by revisionist historians, scientists, and cultural critics explore the connection between nature and American culture, analyzing how it is packaged and presented at places such as Sea World and the Nature Company stores')]

- We're getting correct books based on description. However, we want to show users details like title, author etc, instead of long descriptions.

In [13]:
books[books["isbn13"]== int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_description,title_and_subtitle,tagged_description
462,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5SAOqO2UC&printsec=frontcover&img=1&zoom=1&source=gb...,"First published more than three decades ago, this reissue of Rachel Carson's award-winning class...",1998.0,4.39,112.0,1160.0,0,The Sense of Wonder,"9780067575208 First published more than three decades ago, this reissue of Rachel Carson's award..."

In [15]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int =10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [16]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_description,title_and_subtitle,tagged_description
107,9780060192501,006019250X,The Illustrated Alchemist,Paulo Coelho;Alan R. Clarke;Moebius,Fiction,http://books.google.com/books/content?id=1YX2usKBAMIC&printsec=frontcover&img=1&zoom=1&source=gb...,"This fable aims teaches the reader to open their mind, listen to their heart and most importantl...",1998.0,3.85,198.0,236.0,0,The Illustrated Alchemist: A Fable About Following Your Dream,"9780060192501 This fable aims teaches the reader to open their mind, listen to their heart and m..."
150,9780060546571,0060546573,Three Rotten Eggs,Gregory Maguire,Juvenile Fiction,http://books.google.com/books/content?id=t2pWlCpY3jQC&printsec=frontcover&img=1&zoom=1&source=gb...,The students of Miss Earth's class in rural Vermont experience an eventful spring when they beco...,2005.0,3.74,240.0,76.0,0,Three Rotten Eggs,9780060546571 The students of Miss Earth's class in rural Vermont experience an eventful spring ...
227,9780060765453,0060765453,The Chronicles of Narnia Movie Tie-in Edition (adult),C. S. Lewis,Fiction,http://books.google.com/books/content?id=4qVxvQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,"When Digory and Polly try to return the wicked witch Jadis to her own world, the magic gets mixe...",2005.0,4.26,766.0,1099.0,0,The Chronicles of Narnia Movie Tie-in Edition (adult),"9780060765453 When Digory and Polly try to return the wicked witch Jadis to her own world, the m..."
235,9780060782139,0060782137,Time For Kids: Butterflies!,Editors of TIME For Kids,Juvenile Nonfiction,http://books.google.com/books/content?id=OdZxnI53jj4C&printsec=frontcover&img=1&zoom=1&source=gb...,"Butterflies There are 20,000 different kinds of butterflies in the world. Many have brightly col...",2006.0,4.00,32.0,20.0,0,Time For Kids: Butterflies!,"9780060782139 Butterflies There are 20,000 different kinds of butterflies in the world. Many hav..."
277,9780060885373,0060885378,Little House in the Big Woods,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=7JctNysS3xkC&printsec=frontcover&img=1&zoom=1&source=gb...,"A year in the life of two young girls growing up on the Wisconsin frontier, as they help their m...",2007.0,4.18,198.0,193862.0,0,Little House in the Big Woods,"9780060885373 A year in the life of two young girls growing up on the Wisconsin frontier, as the..."
449,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDWiHI7m4C&printsec=frontcover&img=1&zoom=1&source=gb...,"Even the youngest child can enjoy a special adaptation of a classic Little House tale, as Laura ...",1999.0,4.17,32.0,302.0,0,The Deer in the Wood,9780064434980 Even the youngest child can enjoy a special adaptation of a classic Little House t...
462,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5SAOqO2UC&printsec=frontcover&img=1&zoom=1&source=gb...,"First published more than three decades ago, this reissue of Rachel Carson's award-winning class...",1998.0,4.39,112.0,1160.0,0,The Sense of Wonder,"9780067575208 First published more than three decades ago, this reissue of Rachel Carson's award..."
907,9780143037392,0143037390,The Read-aloud Handbook,Jim Trelease,Language Arts & Disciplines,http://books.google.com/books/content?id=B2_yUfmc6dsC&printsec=frontcover&img=1&zoom=1&source=gb...,"Explains the importance of reading aloud to children, offers guidance on how to set up a read-al...",2006.0,4.40,432.0,4122.0,0,The Read-aloud Handbook,"9780143037392 Explains the importance of reading aloud to children, offers guidance on how to se..."
1151,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,Eric Carle's children's classic is the story of a very small and very hungry caterpillar who man...,1994.0,4.29,26.0,340101.0,0,The Very Hungry Caterpillar,9780241003008 Eric Carle's children's classic is the story of a very small and very hungry cater...
1171,9780262570213,0262570211,Theory of Colours,Johann Wolfgang von Goethe;Donald Eastlake,Art,http://books.google.com/books/content?id=1Jjv0oVT0x0C&printsec=frontcover&img=1&zoom=1&source=gb...,"By closely following Goethe's explanations of the color phenomena, the reader may become so divo...",1970.0,4.07,423.0,669.0,0,Theory of Colours,"9780262570213 By closely following Goethe's explanations of the color phenomena, the reader may ..."
1187,9780285647879,0285647873,The Wanderer,Knut Hamsun;Gunnvor Stallybrass,English fiction,http://books.google.com/books/content?id=RU1_QgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,It has always been a pleasure to me to watch the flowers and insects in their struggle to keep a...,2001.0,3.96,164.0,672.0,0,The Wanderer,9780285647879 It has always been a pleasure to me to watch the flowers and insects in their stru...
1747,9780374299194,0374299196,The Discomfort Zone,Jonathan Franzen,Biography & Autobiography,http://books.google.com/books/content?id=Z2vOAwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gb...,"The author describes growing up in a family of all boys in Webster Groves, Missouri, reflecting ...",2006.0,3.39,195.0,4660.0,0,The Discomfort Zone: A Personal History,"9780374299194 The author describes growing up in a family of all boys in Webster Groves, Missour..."
1861,9780375802430,0375802436,Flap Your Wings,NaN,Juvenile Fiction,http://books.google.com/books/content?id=yK46lkqpJ1cC&printsec=frontcover&img=1&zoom=1&source=gb...,"Two birds unwittingly hatch an alligator egg, which has been accidently placed in their nest, an...",2000.0,4.24,48.0,1228.0,0,Flap Your Wings,"9780375802430 Two birds unwittingly hatch an alligator egg, which has been accidently placed in ..."
1863,9780375812934,0375812938,Jurassic Park Institute Dinosaur Field Guide,Thomas R. Holtz;M. K. Brett-Surman,Juvenile Nonfiction,http://books.google.com/books/content?id=vW3hmLeu0L4C&printsec=frontcover&img=1&zoom=1&source=gb...,"Discusses dinosaur research and what can be learned from it, providing information about the age...",2001.0,4.08,160.0,2.0,0,Jurassic Park Institute Dinosaur Field Guide,"9780375812934 Discusses dinosaur research and what can be learned from it, providing information..."
1925,9780385040204,0385040202,Your Child's Self-esteem,Dorothy Corkille Briggs,Family & Relationships,http://books.google.com/books/content?id=klpvGJllL80C&printsec=frontcover&img=1&zoom=1&source=gb...,Discusses the ways in which parental attitudes shape the child's concept of himself and offers g...,1975.0,4.26,368.0,179.0,0,Your Child's Self-esteem: The Key to Life,9780385040204 Discusses the ways in which parental attitudes shape the child's concept of himsel...
1955,9780385334303,0385334303,The Naked Ape,Desmond Morris,Science,http://books.google.com/books/content?id=CS-GPwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,"Examines sex, child rearing, fighing, feeding habits, and exploration of man in an attempt to es...",1999.0,3.95,256.0,6479.0,0,The Naked Ape: A Zoologist's Study of the Human Animal,"9780385334303 Examines sex, child rearing, fighing, feeding habits, and exploration of man in an..."
1979,9780385423397,038542339X,The Art of the Personal Essay,Phillip Lopate,Literary Collections,http://books.google.com/books/content?id=XLyxV9JxyGQC&printsec=frontcover&img=1&zoom=1&source=gb...,"Essays by writers representing various cultures and eras, from ancient Greece to the present, in...",1995.0,4.19,777.0,2096.0,0,The Art of the Personal Essay: An Anthology from the Classical Era to the Present,"9780385423397 Essays by writers representing various cultures and eras, from ancient Greece to t..."
2053,9780393311396,0393311392,Eight Little Piggies,Stephen Jay Gould,Nature,http://books.google.com/books/content?id=_kOoVw0SIhUC&printsec=frontcover&img=1&zoom=1&edge=curl...,"In the sixth volume of essays from Natural History magazine, a science writer discusses environm...",1994.0,4.09,480.0,699.0,0,Eight Little Piggies: Reflections in Natural History,"9780393311396 In the sixth volume of essays from Natural History magazine, a science writer disc..."
2056,9780393315110,0393315118,Uncommon Ground: Rethinking the Human Place in Nature,William Cronon,Law,http://books.google.com/books/content?id=w04mjve7XekC&printsec=frontcover&img=1&zoom=1&source=gb...,"Essays by revisionist historians, scientists, and cultural critics explore the connection betwee...",1996.0,4.16,560.0,649.0,0,Uncommon Ground: Rethinking the Human Place in Nature,"9780393315110 Essays by revisionist historians, scientists, and cultural critics explore the con..."
2147,9780399226908,0399226907,"Eric Carle's Very Little Library: The very hungry caterpillar (1st board book ed., 1994)",NaN,Caterpillars,http://books.google.com/books/content?id=oiMwvgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,"Colorful and full of imagination, the world of Eric Carle is a delight! Sings songs, cook, and c...",2003.0,4.29,13.0,3773.0,0,"Eric Carle's Very Little Library: The very hungry caterpillar (1st board book ed., 1994)","9780399226908 Colorful and full of imagination, the world of Eric Carle is a delight! Sings song..."
2628,9780451529060,0451529065,The Origin of Species,Charles Darwin,Fiction,http://books.google.com/books/content?id=xxCZsO5hWJoC&printsec=frontcover&img=1&zoom=1&source=gb...,"States the evidence for a theory of evolution, explains how evolution takes place, and discusses...",2003.0,3.99,576.0,760.0,0,The Origin of Species: By Means of Natural Selection of the Preservation of Favoured Races in th...,"9780451529060 States the evidence for a theory of evolution, explains how evolution takes place,..."
2726,9780486276809,0486276805,The Secret Garden Coloring Book,Frances Hodgson Burnett,Juvenile Nonfiction,http://books.google.com/books/content?id=sxHdAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl...,Ten-year-old Mary comes to live in a lonely house on the Yorkshire moors and discovers an invali...,2014.0,4.25,48.0,4.0,0,The Secret Garden Coloring Book,9780486276809 Ten-year-old Mary comes to live in a lonely house on the Yorkshire moors and disco...
2727,9780486280233,0486280233,The Adventures of Jimmy Skunk,Thornton W. Burgess;Harrison Cady;Thea Kliros,Juvenile Fiction,http://books.google.com/books/content?id=dVZ8DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl...,Relates how Jimmy Skunk repays Peter Rabbit for a practical joke and what happens when he and Un...,1994.0,4.13,96.0,258.0,0,The Adventures of Jimmy Skunk,9780486280233 Relates how Jimmy Skunk repays Peter Rabbit for a practical joke and what happens ...
2762,9780486450063,0486450066,On the Origin of Species,Charles Darwin,Science,http://books.google.com/books/content?id=PoMyAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl...,"States the evidence for a theory of evolution, explains how evolution takes place, and discusses...",2006.0,3.99,336.0,171.0,0,On the Origin of Species: By Means of Natural Selection,"9780486450063 States the evidence for a theory of evolution, explains how evolution takes place,..."
2802,9780517189603,0517189607,The Secret Garden,Frances Hodgson Burnett,Juvenile Fiction,http://books.google.com/books/content?id=oGNbnTQdiJ4C&printsec=frontcover&img=1&zoom=1&source=gb...,A ten-year-old orphan comes to live in a lonely house on the Yorkshire moors where she discovers...,1998.0,4.13,331.0,725384.0,0,The Secret Garden,9780517189603 A ten-year-old orphan comes to live in a lonely house on the Yorkshire moors where...
2826,9780520251748,0520251741,Gardening with a Wild Heart,Judith Larner Lowry,Gardening,http://books.google.com/books/content?id=Kit0gMn0X90C&printsec=frontcover&img=1&zoom=1&edge=curl...,"Essays discuss wildflower gardening, the ecology of native grasses, wildland seed collecting, pr...",2007.0,4.29,267.0,11.0,0,Gardening with a Wild Heart: Restoring California's Native Landscapes at Home,"9780520251748 Essays discuss wildflower gardening, the ecology of native grasses, wildland seed ..."
3060,9780571161157,0571161154,The Complete Herbal Handbook for the Dog and Cat,Juliette de Baïracli Levy,Pets,http://books.google.com/books/content?id=BaPewAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,Dog and cat owners are becoming increasingly concerned about the saftey of processed pet food an...,1991.0,4.29,368.0,100.0,0,The Complete Herbal Handbook for the Dog and Cat,9780571161157 Dog and cat owners are becoming increasingly concerned about the saftey of process...
3113,9780590100564,0590100564,Common Ground,Molly Bang,Juvenile Nonfiction,http://books.google.com/books/content?id=LSpkG31BYDUC&printsec=frontcover&img=1&zoom=1&edge=curl...,Imagines a village in which there are too many people consuming shared resources and discusses t...,1997.0,3.75,40.0,92.0,0,"Common Ground: The Water, Earth, and Air We Share",9780590100564 Imagines a village in which there are too many people consuming shared resources a...
3179,9780618249060,0618249060,Silent Spring,Rachel Carson,Nature,http://books.google.com/books/content?id=HeR1l0V0r54C&printsec=frontcover&img=1&zoom=1&edge=curl...,Discusses the reckless annihilation of fish and birds by the use of pesticides and warns of the ...,2002.0,3.97,378.0,28033.0,0,Silent Spring,9780618249060 Discusses the reckless annihilation of fish and birds by the use of pesticides and...
3283,9780671631987,0671631985,Teach Your Child to Read in 100 Easy Lessons,Siegfried Engelmann;Phyllis Haddox;Elaine Bruner,Education,http://books.google.com/books/content?id=MUucJV0dRaIC&printsec=frontcover&img=1&zoom=1&edge=curl...,"With more than half a million copies in print, Teach Your Child to Read in 100 Easy Lessons is t...",1986.0,4.15,395.0,2083.0,0,Teach Your Child to Read in 100 Easy Lessons,"9780671631987 With more than half a million copies in print, Teach Your Child to Read in 100 Eas..."
3359,9780679451211,0679451218,The Sibley Field Guide to Birds of Western North America,NaN,Nature,http://books.google.com/books/content?id=Fd0PAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,A guide for bird enthusiasts specifically designed for use in the field features descriptions of...,2003.0,4.70,473.0,709.0,0,The Sibley Field Guide to Birds of Western North America,9780679451211 A guide for bird enthusiasts specifically designed for use in the field features d...
3542,9780689863110,068986311X,The Eagle,Cynthia Rylant;Preston McDaniels,Juvenile Fiction,http://books.google.com/books/content?id=cxC9XoIu7sQC&printsec=frontcover&img=1&zoom=1&edge=curl...,"Two mice that live in a lighthouse along with a dog, a cat, and another mouse, lose their compas...",2005.0,4.08,64.0,155.0,0,The Eagle,"9780689863110 Two mice that live in a lighthouse along with a dog, a cat, and another mouse, los..."
3915,9780761316800,0761316809,It's Winter!,Linda Glaser,Juvenile Nonfiction,http://books.google.com/books/content?id=eSCmKfZGvmcC&printsec=frontcover&img=1&zoom=1&source=gb...,"A child observes the coming of winter and its effects on the weather, animals, and plants. Inclu...",2002.0,3.63,32.0,80.0,0,It's Winter!,"9780761316800 A child observes the coming of winter and its effects on the weather, animals, and..."
4113,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4PAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,Children will discover the exciting world of their own backyard in this introduction to familiar...,2001.0,3.89,16.0,180.0,0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the exciting world of their own backyard in this introducti...
4114,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHPQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,"Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photog...",2002.0,3.78,20.0,9.0,0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutrat..."
4117,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops and Puddles,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIAAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,A very special puddle sets Violet the mouse off on her latest nature discovery. It is through th...,2002.0,3.25,18.0,16.0,0,Baby Einstein: What Does Violet See? Raindrops and Puddles,9780786808717 A very special puddle sets Violet the mouse off on her latest nature discovery. It...
4168,9780789422132,0789422131,Flowers,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=1DsEAAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gb...,Describes the physical characteristics and life cycles of flowers and examines kinds of garden f...,1997.0,4.00,64.0,8.0,0,Flowers,9780789422132 Describes the physical characteristics and life cycles of flowers and examines kin...
4169,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj2INT1QC&printsec=frontcover&img=1&zoom=1&source=gb...,"Photographs and text explore the anatomy and life cycle of trees, examining the different kinds ...",2000.0,4.07,64.0,5.0,0,Tree,"9780789458209 Photographs and text explore the anatomy and life cycle of trees, examining the di..."
4327,9780811205467,0811205460,Turtle Island,Gary Snyder,Poetry,http://books.google.com/books/content?id=xilff6LAWAcC&printsec=frontcover&img=1&zoom=1&edge=curl...,"These Pulitzer Prize-winning poems and essays by the author of No Nature range from the lucid, l...",1974.0,4.09,112.0,3717.0,0,Turtle Island,9780811205467 These Pulitzer Prize-winning poems and essays by the author of No Nature range fro...
4642,9780887511127,0887511120,Teaching the World's Children,Mary Ashworth;Patricia Wakefield,Education,http://books.google.com/books/content?id=mp4FhKqKN7MC&printsec=frontcover&img=1&zoom=1&edge=curl...,"The language young children use is the language they learn. In clear, practical terms, this prim...",2004.0,3.50,101.0,4.0,0,Teaching the World's Children: ESL for Ages Three to Seven,"9780887511127 The language young children use is the language they learn. In clear, practical te..."
4658,9780898599596,0898599598,The Ecological Approach to Visual Perception,James Jerome Gibson,Psychology,http://books.google.com/books/content?id=DrhCCWmJpWUC&printsec=frontcover&img=1&zoom=1&edge=curl...,"This is a book about how we see: the environment around us (its surfaces, their layout, and thei...",1986.0,4.28,348.0,122.0,0,The Ecological Approach to Visual Perception,"9780898599596 This is a book about how we see: the environment around us (its surfaces, their la..."
4691,9780940450202,0940450208,"The Leatherstocking Tales: The pioneers, or The sources of the Susquehanna. The last of the Mohi...",James Fenimore Cooper,"Bumppo, Natty (Fictitious character)",http://books.google.com/books/content?id=clUU8L3hhAsC&printsec=frontcover&img=1&zoom=1&edge=curl...,"Natty Bumpo and Chingachgook, bring alive the early 1700's when Americans, French, and Huron wer...",1985.0,3.87,1347.0,344.0,0,"The Leatherstocking Tales: The pioneers, or The sources of the Susquehanna. The last of the Mohi...","9780940450202 Natty Bumpo and Chingachgook, bring alive the early 1700's when Americans, French,..."

---